### ISSUE TITLE
Razor Pilots require a team when they should not need one.

### ISSUE THREAD

**Issue by Soyvolon** [501stLegionA3/FiveOhFirstDataCore#153]
# Describe the bug
Pilots need a team (Alpha or Bravo) to show up in the roster properly.

![image](https://user-images.githubusercontent.com/16871668/128419224-3f11609f-8ef2-4810-96d7-602578d71b01.png)

# Expected behavior
Pilots show up based upon their Flight without the team affecting anything.

**Comment by Soyvolon** [comment]
I believe this is an error with the `IAssignable<int>` for Razor objects but am unsure.

**Comment by jdoxley** [comment]
We can get some interesting behavior with this because of the way that the Razor objects are setup. Would probably be best to change the way we assign for razor to look off of slot instead of team.

![chrome_2021-08-07_18-38-24](https://user-images.githubusercontent.com/25972715/128618005-e5b3ab93-f3b5-4857-9398-f003434d608c.png)
![chrome_2021-08-07_18-38-34](https://user-images.githubusercontent.com/25972715/128618006-39a2c7b9-57e8-4fcb-8420-53c22fb7c052.png)
